### ISSUE TITLE
[Tableau Feedback] Remove connectionRequired.js for performance gains

### ISSUE THREAD

**Issue by pvanderknyff** [dremio-hub/tableau-connector#1]
Because we're spinning up a javascript engine from Tableau's c++ code to run javascript, we now recommend implementing that logic in xml in the connecitonResolver.tdr file.

You can see an example in our samples [here](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/connectionResolver.tdr#L7). It should be fairly trivial to port your current logic over, since your script has no conditionals.

Let me know you if have any questions, or if there are clarifications I can make.

**Comment by kylep-dremio** [comment]
Addressed.
