### ISSUE TITLE
[Tableau Feedback] Create a properties builder script

### ISSUE THREAD

**Issue by pvanderknyff** [dremio-hub/tableau-connector#2]
Since your connector was started, we've changed our samples to better reflect best practices for JDBC. You can read about the connection properties script in our [documentation](https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-properties), and we have a [sample jdbc plugin](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/plugins/postgres_jdbc) that uses the [connection properties script](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/connectionProperties.js). Note that you'll need to change your connection builder script to match the sample as well.

Basically, the formatted params are set int he connection properties script. This has implications in Tableau, and will make sure we treat the properties correctly (for example, not logging the password value). 

Note that connection properties has two different possible return values, either a javascript object or a string formatted to have key=value. The javascript object is preferred since it does not have trouble with an equals sign in a property, but was only introduced in 2019.4.1.

Let me know you if have any questions, or if there are clarifications I can make.

**Comment by kylep-dremio** [comment]
@pvanderknyff believe this should be addressed. Please recheck.
