### ISSUE TITLE
[TDVT Failure] INT conversion rounds instead of truncates

### ISSUE THREAD

**Issue by pvanderknyff** [dremio-hub/tableau-connector#6]
When Tableau casts a decimal number as an integer, the [expected behavior is that we truncate results to the closest integer toward zero](https://help.tableau.com/current/pro/desktop/en-us/functions_functions_typeconversion.htm). For example:
INT(17.86) = 17

Dremio, however, seems to be rounding to the nearest to the nearest integer:
INT(17.86) = 18

To fix this, you should add a floor or a trunc call to the int conversion formula here: https://github.com/dremio-hub/tableau-connector/blob/master/dialect_plugin.tdd#L374

This affects the cast.int and the cast.int.nulls tests.

**Comment by kylep-dremio** [comment]
Done
